### ISSUE TITLE
Unexpectedly Large Package Build

### ISSUE THREAD

**Issue by ryan-mahoney** [final-form/react-final-form-html5-validation#1]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

The distributed builds are huge, for example, the `react-final-form-html5-validation.es.js` is 670kb. It also contains references to things like `__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner` which doesn't seem right.

### What is the expected behavior?

This looks like a small library, the build should also be small.

### What's your environment?

final-form: ^4.8.3

react-final-form-html5-validation: 1.0.0

**Comment by ryan-mahoney** [comment]
Another clue, when I build my project, it says:
```[BABEL] Note: The code generator has deoptimised the styling of "/Users/ryanmahoney/Documents/ecommerce/app/node_modules/react-final-form-html5-validation/dist/react-final-form-html5-validation.es.js" as it exceeds the max of "500KB"```

Removing `react-final-form-html5-validation` (by just aliasing it to `react-final-form in my webpack config) shaves off ~100Kb!

**Comment by erikras** [comment]
That's pretty weird considering [the actual code](https://github.com/final-form/react-final-form-html5-validation/blob/master/src/Html5ValidationField.js) is `< 3kb`. [Bundlephobia confirms](https://bundlephobia.com/result?p=react-final-form-html5-validation@1.0.0) it's almost 100kb unzipped. It sure looks like the peer deps are properly specified as "external" in the `rollup.config.js`. 🤔

**Comment by ryan-mahoney** [comment]
Yeah, I wanted to be more helpful and open a PR w/ a fix, but I've not actually bundled a library with rollup before. Hope it's an easy fix, this is a great lib  ;)

**Comment by Andarist** [comment]
This can be closed - forgot to put `fixes #1` in my PR.

**Comment by ryan-mahoney** [comment]
Will you be pushing a new version to NPM?

**Comment by erikras** [comment]
Published fix in [`v1.0.1`](https://github.com/final-form/react-final-form-html5-validation/releases/tag/v1.0.1).

`dist/react-final-form-html5-validation.es.js` went from `730K` to `5.4K`. 😱
